### PR TITLE
Pack of tests and fixes

### PR DESCRIPTION
**Pull request by KlausC**
Add test cases for the `ArbComplex`type.

A few bug and simplifications were made to the source code,
as revealed by test failures, and to simplify test coverage.

Some test cases are declared 'broken', have to be fixed.

The more test cases are developed, the more glitches in the software are detected, which are removed.

For the releases before nightly, on windows, CI cannot load the required packages. Those runs were removed from the CI matrix.

### CODE REVIEW

**Comment by KlausC** [comment]
Will further increase test coverage and remove redundancies.

**Comment by P3109** [comment]
if/when you want this merged -- change it from draft status

**Comment by KlausC** [comment]
This state of development is now more stable then ever, also if it is not perfect yet. Can be reviewed/merged.

**Comment by JeffreySarnoff** [comment]
I thought I had merged this long before -- thank you!

**Comment by JeffreySarnoff** [comment]
Hi Klaus,
We have a report of a glitch that followed this update ..
Please take a look and let me know if you see a fix.
https://github.com/JeffreySarnoff/ArbNumerics.jl/issues/68#issuecomment-2096986328

**Pull request merged**
