### PR TITLE
Fft

### PR DESCRIPTION
**Pull request by orkolorko**
Dear Jeffrey,
I implemented a binding to the DFT library from ARB.
It takes an Array of ArbComplex, applies the DFT rigorously.

The function can be called by ArbNumerics.ArbDFT.

Some work was needed to implement ArbComplexVector, 
but the interface needs not to be exposed, it is used only in an accessory way to
compute the DFT.

Best wishes
Isaia

### CODE REVIEW

**Comment by orkolorko** [comment]
I will work somewhat more on the interface.

**Comment by orkolorko** [comment]
Do you have any preferences on the interface? At the moment it takes an Array{ArbComplex, 1} and returns and ArbComplexVector that, for all that matters, behaves as an Array{ArbComplex, 1}.

Do you have any design idea on how you would like the interface? ArbComplexVector can be passed to Arb Linear Algebra without much work...

**Comment by JeffreySarnoff** [comment]
looking

**Comment by JeffreySarnoff** [comment]
Why define `ArbComplexVector`  as something other than `Array{ArbComplex,1}`?
There are complexities with the Arb interface to `ArbComplex` and if anything is off, in some circumstances it can crash Julia.

**Comment by orkolorko** [comment]
This is because the ccall function takes a Pointer to an array of ArbComplex, whose memory is owned by C.
I mimicked the interface of ArbComplexMatrix.

Do you think is better/possible to pass an Array{ArbComplex, 1} as a pointer to the C function arbdft?

**Comment by JeffreySarnoff** [comment]
ArbComplexMatrix is conforming to a C struct that exists in Arb.  Unfortunately, there is no ArbComplexVector C struct that exists in Arb.  It may well be that your code works appropriately, it is just a departure from prior practice ... I will look at the ccall more carefully and if I see no hitch, merge this.

**Comment by JeffreySarnoff** [comment]
It appears that ArbDFT uses Array{ArbComplex,1} but ArbInverseDFT uses ArbComplexVector?
If ArbDFT works with Array{ArbComplex,1} then ArbInverseDFT should work with that too.
We need a few test cases.

**Comment by JeffreySarnoff** [comment]
It would make it more difficult to use the result of the DFT for other purposes if we impose some structure other than Array{ArbComplex,1}.  Also, a minor point, the exported names of these should be `DFT` and `InverseDFT` rather than `ArbDFT` etc, none of the other functions are called `Arb_`, that form is used for the types only.
Thanks again for keeping on this -- it is a good contribution.

**Comment by orkolorko** [comment]
> It appears that ArbDFT uses Array{ArbComplex,1} but ArbInverseDFT uses ArbComplexVector?
If ArbDFT works with Array{ArbComplex,1} then ArbInverseDFT should work with that too.
I think ArbDFT should map the obtained result ArbComplexVector -> Array{ArbComplex,1} via a function call internal to ArbDFT so it returns an Array{ArbComplex,1}.

Ok, I will implement this, so that ArbComplexVector is only needed as an internal.

**Comment by orkolorko** [comment]
So, I've modified the interface. I`m currently investigating if the memory can be owned directly by Julia. It seems to me that this would make thing much more coherent and avoid memory leaks (or the fact that the gc does not see the object to be big)

**Comment by orkolorko** [comment]
I scrapped totally the ArbComplexVector interface, now the DFT function allocates and deallocates the memory in C space and calls the DFT there. 
This is done since I'm not sure the Garbage Collector finalizes the ArbComplexVector when necessary.

**Comment by orkolorko** [comment]
I scrapped the whole ArbComplexVector objects, now the DFT is taking care of allocating and deallocating the memory in C space and calling the DFT from the C library, since I was not sure of the behaviour of the Garbage Collector with respect to the ArbComplexVector

**Comment by JeffreySarnoff** [comment]
That is good. I am happy to merge this -- I don't understand why the build is failing?

**Comment by JeffreySarnoff** [comment]
It is a travis problem. merging.

**Comment by JeffreySarnoff** [comment]
I changed the names to `dft` and `inverse_dft` to comport with the other names.
I added simple conversions so they accept ArbReals and ArbFloats also.

**Pull request merged**
